
CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    country_code VARCHAR(5) DEFAULT '91',
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    company_id VARCHAR(36),
    depot_id VARCHAR(36),
    transporter_id VARCHAR(36),
    transporter_name VARCHAR(255),
    email VARCHAR(255),
    otp_verified BOOLEAN DEFAULT FALSE,
    password_set BOOLEAN DEFAULT TRUE,
    is_master_admin BOOLEAN DEFAULT FALSE,
    assigned_products TEXT,
    assigned_depots TEXT,
    excluded_products TEXT,
    excluded_depots TEXT,
    created_by VARCHAR(36),
    created_at DATETIME NOT NULL,
    UNIQUE KEY uk_mobile (mobile),
    INDEX idx_role (role),
    INDEX idx_company (company_id),
    INDEX idx_depot (depot_id),
    INDEX idx_transporter (transporter_id)
);

CREATE TABLE otps (
    id VARCHAR(36) PRIMARY KEY,
    mobile VARCHAR(20) NOT NULL,
    country_code VARCHAR(5) NOT NULL,
    otp_code VARCHAR(10) NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    verified BOOLEAN DEFAULT FALSE,
    attempts INT DEFAULT 0,
    created_at DATETIME NOT NULL,
    expires_at DATETIME NOT NULL,
    INDEX idx_mobile_purpose (mobile, purpose),
    INDEX idx_expires_at (expires_at)
);

CREATE TABLE companies (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    trade_name VARCHAR(255),
    logo_file_id VARCHAR(255),
    location VARCHAR(255),
    city VARCHAR(100),
    district VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(50) DEFAULT 'India',
    pin_code VARCHAR(10),
    hsn_code VARCHAR(50),
    product_description TEXT,
    gst_applicability VARCHAR(50),
    gst_number VARCHAR(50),
    website VARCHAR(255),
    primary_email VARCHAR(255),
    secondary_email VARCHAR(255),
    address TEXT,
    landmark VARCHAR(255),
    emergency_contact VARCHAR(50),
    whatsapp_number VARCHAR(50),
    telephone VARCHAR(50),
    pan_number VARCHAR(50),
    bank_name VARCHAR(255),
    bank_account_number VARCHAR(50),
    ifsc_code VARCHAR(50),
    contact_person_name VARCHAR(255),
    contact_person_mobile VARCHAR(50),
    company_type VARCHAR(50) DEFAULT 'Client',
    is_client BOOLEAN DEFAULT FALSE,
    added_on DATETIME,
    added_by VARCHAR(36),
    users TEXT,
    created_at DATETIME NOT NULL,
    INDEX idx_name (name)
);

CREATE TABLE company_users (
    id VARCHAR(36) PRIMARY KEY,
    company_id VARCHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    title VARCHAR(100),
    date_of_birth VARCHAR(50),
    marital_status VARCHAR(20),
    date_of_anniversary VARCHAR(50),
    mobile_number VARCHAR(50),
    email VARCHAR(255),
    whatsapp_number VARCHAR(50),
    emergency_contact VARCHAR(50),
    address TEXT,
    city VARCHAR(100),
    district VARCHAR(100),
    state VARCHAR(100),
    pin_code VARCHAR(20),
    country VARCHAR(50) DEFAULT 'India',
    pan_number VARCHAR(50),
    aadhaar_number VARCHAR(50),
    photo_url VARCHAR(255),
    remarks TEXT,
    created_at DATETIME NOT NULL,
    INDEX idx_company (company_id)
);

CREATE TABLE transporters (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    trade_name VARCHAR(255),
    contact_person_name VARCHAR(255),
    mobile_number VARCHAR(50),
    email VARCHAR(255),
    address TEXT,
    gst_number VARCHAR(50),
    industry_type VARCHAR(100),
    company_ids TEXT,
    users TEXT,
    created_at DATETIME NOT NULL,
    INDEX idx_name (name)
);

CREATE TABLE trucks (
    id VARCHAR(36) PRIMARY KEY,
    vehicle_number VARCHAR(50) NOT NULL,
    transporter_id VARCHAR(36),
    transporter_name VARCHAR(255),
    capacity_mt FLOAT,
    tare_weight_mt FLOAT,
    driver_name VARCHAR(255),
    driver_mobile VARCHAR(50),
    helper_name VARCHAR(255),
    helper_mobile VARCHAR(50),
    drivers TEXT,
    current_status VARCHAR(50) DEFAULT 'Idle',
    front_photo VARCHAR(255),
    back_photo VARCHAR(255),
    photos TEXT,
    fitness_certificate TEXT,
    fitness_valid_upto VARCHAR(50),
    insurance TEXT,
    insurance_valid_upto VARCHAR(50),
    tax TEXT,
    tax_valid_upto VARCHAR(50),
    pollution TEXT,
    pollution_valid_upto VARCHAR(50),
    rc TEXT,
    permit_valid_upto VARCHAR(50),
    registration_date VARCHAR(50),
    m_parivaahan VARCHAR(255),
    driver_license TEXT,
    driver_photo VARCHAR(255),
    driver_aadhaar TEXT,
    helper1_name VARCHAR(255),
    helper1_mobile VARCHAR(50),
    helper1_aadhaar TEXT,
    helper1_photo VARCHAR(255),
    helper2_name VARCHAR(255),
    helper2_mobile VARCHAR(50),
    helper2_aadhaar TEXT,
    helper2_photo VARCHAR(255),
    created_at DATETIME NOT NULL,
    UNIQUE KEY uk_vehicle_number (vehicle_number),
    INDEX idx_transporter (transporter_id)
);

CREATE TABLE products (
    id VARCHAR(36) PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    product_code VARCHAR(100),
    product_description TEXT,
    unit_of_measurement VARCHAR(20) DEFAULT 'MT',
    category VARCHAR(100),
    hsn_code VARCHAR(50),
    assigned_roles TEXT,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uk_product_code (product_code)
);

CREATE TABLE depots (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    address TEXT,
    contact_person_name VARCHAR(255),
    contact_mobile VARCHAR(50),
    storage_capacity FLOAT,
    warehouse_type VARCHAR(100),
    assigned_roles TEXT,
    created_at DATETIME NOT NULL,
    INDEX idx_name (name)
);

CREATE TABLE depot_inventory (
    id VARCHAR(36) PRIMARY KEY,
    depot_id VARCHAR(36) NOT NULL,
    company_id VARCHAR(36),
    depot_name VARCHAR(255) NOT NULL,
    product_id VARCHAR(36) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_code VARCHAR(100),
    total_received FLOAT DEFAULT 0,
    total_dispatched FLOAT DEFAULT 0,
    available_quantity FLOAT DEFAULT 0,
    last_updated DATETIME,
    UNIQUE KEY uk_depot_product (depot_id, product_id),
    INDEX idx_product (product_id)
);

CREATE TABLE company_inventory (
    id VARCHAR(36) PRIMARY KEY,
    company_id VARCHAR(36) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    product_id VARCHAR(36) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_code VARCHAR(100),
    total_received FLOAT DEFAULT 0,
    total_dispatched FLOAT DEFAULT 0,
    available_quantity FLOAT DEFAULT 0,
    last_updated DATETIME,
    UNIQUE KEY uk_company_product (company_id, product_id),
    INDEX idx_product (product_id)
);

CREATE TABLE delivery_orders (
    id VARCHAR(36) PRIMARY KEY,
    transport_mode VARCHAR(20) DEFAULT 'Road',
    from_company_id VARCHAR(36),
    from_company_name VARCHAR(255),
    product_id VARCHAR(36),
    product_name VARCHAR(255),
    product_code VARCHAR(100),
    total_quantity_mt FLOAT NOT NULL,
    destination_type VARCHAR(20) DEFAULT 'Depot',
    to_depot_id VARCHAR(36),
    to_depot_name VARCHAR(255),
    to_company_id VARCHAR(36),
    to_company_name VARCHAR(255),
    loading_siding_id VARCHAR(36),
    loading_siding_name VARCHAR(255),
    loading_siding_code VARCHAR(50),
    destination_siding_id VARCHAR(36),
    destination_siding_name VARCHAR(255),
    destination_siding_code VARCHAR(50),
    remarks TEXT,
    do_copy_file_id VARCHAR(255),
    client_do_number VARCHAR(100),
    client_do_date VARCHAR(50),
    do_order_no VARCHAR(100),
    do_date DATETIME,
    lifted_quantity_mt FLOAT DEFAULT 0,
    remaining_quantity_mt FLOAT DEFAULT 0,
    status VARCHAR(50) DEFAULT 'Open',
    added_by VARCHAR(36),
    added_by_name VARCHAR(255),
    created_at DATETIME NOT NULL,
    INDEX idx_status (status),
    INDEX idx_product (product_id),
    INDEX idx_to_company (to_company_id),
    INDEX idx_to_depot (to_depot_id)
);

CREATE TABLE liftings (
    id VARCHAR(36) PRIMARY KEY,
    lifting_type VARCHAR(20) DEFAULT 'Primary',
    transport_mode VARCHAR(20) DEFAULT 'Road',
    company_id VARCHAR(36),
    delivery_order_id VARCHAR(36),
    delivery_order_no VARCHAR(100),
    product_id VARCHAR(36),
    product_name VARCHAR(255),
    product_code VARCHAR(100),
    quantity_mt FLOAT NOT NULL,
    loading_point_type VARCHAR(20) DEFAULT 'Company',
    loading_point_id VARCHAR(36),
    loading_point_name VARCHAR(255),
    date_of_loading DATETIME,
    time_of_loading VARCHAR(50),
    vehicle_id VARCHAR(36),
    vehicle_number VARCHAR(50),
    transporter_name VARCHAR(255),
    driver_name VARCHAR(255),
    driver_mobile VARCHAR(50),
    helper_name VARCHAR(255),
    helper_mobile VARCHAR(50),
    loading_siding_id VARCHAR(36),
    loading_siding_name VARCHAR(255),
    loading_siding_code VARCHAR(50),
    destination_siding_id VARCHAR(36),
    destination_siding_name VARCHAR(255),
    destination_siding_code VARCHAR(50),
    tare_weight_mt FLOAT,
    gross_weight_mt FLOAT,
    net_weight_mt FLOAT,
    weight_slip VARCHAR(255),
    unloading_point_type VARCHAR(20) DEFAULT 'Depot',
    unloading_point_id VARCHAR(36),
    unloading_point_name VARCHAR(255),
    purchase_order_id VARCHAR(36),
    purchase_order_no VARCHAR(100),
    pickup_id VARCHAR(36),
    lifting_no VARCHAR(100),
    loading_status VARCHAR(50) DEFAULT 'Loaded',
    loaded_by VARCHAR(36),
    loaded_by_name VARCHAR(255),
    unloading_status VARCHAR(50) DEFAULT 'Pending',
    date_of_unloading DATETIME,
    time_of_unloading VARCHAR(50),
    verified_by VARCHAR(36),
    verified_by_name VARCHAR(255),
    verified_at DATETIME,
    rejected_by VARCHAR(36),
    rejected_by_name VARCHAR(255),
    rejected_at DATETIME,
    rejection_reason TEXT,
    rescheduled_to VARCHAR(36),
    reschedule_reason TEXT,
    reschedule_count INT DEFAULT 0,
    reschedule_group_id VARCHAR(36),
    final_verified_by VARCHAR(36),
    final_verified_by_name VARCHAR(255),
    final_verified_at DATETIME,
    created_at DATETIME NOT NULL,
    INDEX idx_date_loading (date_of_loading),
    INDEX idx_unloading_status (unloading_status),
    INDEX idx_product (product_id),
    INDEX idx_delivery_order (delivery_order_id),
    INDEX idx_purchase_order (purchase_order_id),
    INDEX idx_pickup (pickup_id),
    INDEX idx_vehicle (vehicle_number)
);

CREATE TABLE pickups (
    id VARCHAR(36) PRIMARY KEY,
    date VARCHAR(50),
    truck_number VARCHAR(50),
    truck_id VARCHAR(36),
    transporter_id VARCHAR(36),
    transporter_name VARCHAR(255),
    company_id VARCHAR(36),
    company_name VARCHAR(255),
    estimated_weight_mt FLOAT,
    driver_phone VARCHAR(50),
    source_id VARCHAR(36),
    source_name VARCHAR(255),
    source_type VARCHAR(50) DEFAULT 'Depot',
    product_id VARCHAR(36),
    product_name VARCHAR(255),
    tare_slip_file_id VARCHAR(255),
    original_schedule_date VARCHAR(50),
    reschedule_count INT DEFAULT 0,
    status VARCHAR(50) DEFAULT 'scheduled',
    created_at DATETIME NOT NULL,
    loading_start_time VARCHAR(50),
    loading_end_time VARCHAR(50),
    purchase_order_id VARCHAR(36),
    purchase_order_no VARCHAR(100),
    purchase_order_company_name VARCHAR(255),
    purchase_order_date VARCHAR(50),
    purchase_order_company_id VARCHAR(36),
    lifting_id VARCHAR(36),
    lifting_no VARCHAR(100),
    rescheduled_to VARCHAR(36),
    reschedule_reason TEXT,
    reschedule_group_id VARCHAR(36),
    verified_by VARCHAR(36),
    verified_by_name VARCHAR(255),
    verified_at DATETIME,
    weight_mt FLOAT,
    weight_slips TEXT,
    loaded_weight_mt FLOAT,
    weightment_slip_file_id VARCHAR(255),
    tare_slip_upload_history TEXT,
    weightment_slip_upload_history TEXT,
    final_verified_by VARCHAR(36),
    final_verified_by_name VARCHAR(255),
    final_verified_at DATETIME,
    INDEX idx_status (status),
    INDEX idx_truck (truck_number),
    INDEX idx_company (company_id)
);

CREATE TABLE purchase_orders (
    id VARCHAR(36) PRIMARY KEY,
    depot_id VARCHAR(36),
    depot_name VARCHAR(255),
    source_type VARCHAR(50) DEFAULT 'Depot',
    to_company_id VARCHAR(36),
    to_company_name VARCHAR(255),
    product_id VARCHAR(36),
    product_name VARCHAR(255),
    product_code VARCHAR(100),
    total_quantity_mt FLOAT NOT NULL,
    remarks TEXT,
    client_po_number VARCHAR(100),
    client_po_date VARCHAR(50),
    po_copy_file_id VARCHAR(255),
    estimated_completion_date VARCHAR(50),
    po_number VARCHAR(100),
    po_date DATETIME,
    dispatched_quantity_mt FLOAT DEFAULT 0,
    remaining_quantity_mt FLOAT DEFAULT 0,
    status VARCHAR(50) DEFAULT 'Open',
    completion_reason TEXT,
    actual_completion_date VARCHAR(50),
    added_by VARCHAR(36),
    added_by_name VARCHAR(255),
    created_at DATETIME NOT NULL,
    INDEX idx_status (status),
    INDEX idx_product (product_id),
    INDEX idx_company (to_company_id)
);

CREATE TABLE verified_trucks (
    id VARCHAR(36) PRIMARY KEY,
    date VARCHAR(50) NOT NULL,
    truck_no VARCHAR(50) NOT NULL,
    transporter VARCHAR(255),
    driver_mobile VARCHAR(50),
    company VARCHAR(255),
    product VARCHAR(255),
    product_id VARCHAR(36),
    po_number VARCHAR(100),
    po_date VARCHAR(50),
    depot VARCHAR(255),
    depot_id VARCHAR(36),
    weight FLOAT,
    verified_by VARCHAR(36),
    tare_slip_file_id VARCHAR(255),
    weightment_slip_file_id VARCHAR(255),
    invoice_added BOOLEAN DEFAULT FALSE,
    invoice_details TEXT,
    shipping_added BOOLEAN DEFAULT FALSE,
    shipping_details TEXT,
    packing_list_added BOOLEAN DEFAULT FALSE,
    packing_list_details TEXT,
    source VARCHAR(255),
    source_id VARCHAR(36),
    source_type VARCHAR(50),
    created_at DATETIME NOT NULL,
    INDEX idx_date (date),
    INDEX idx_truck_no (truck_no)
);

CREATE TABLE permissions (
    id VARCHAR(36) PRIMARY KEY,
    permissions TEXT,
    updated_at DATETIME
);

CREATE TABLE railway_zones (
    id VARCHAR(36) PRIMARY KEY,
    country VARCHAR(50),
    railway_zone VARCHAR(255),
    zone_code VARCHAR(50),
    headquarters VARCHAR(255),
    area_coverage TEXT,
    divisions_allotted TEXT,
    created_at DATETIME NOT NULL
);

CREATE TABLE railway_sidings (
    id VARCHAR(36) PRIMARY KEY,
    siding_name VARCHAR(255) NOT NULL,
    siding_code VARCHAR(50),
    location VARCHAR(255),
    station_name VARCHAR(255),
    state VARCHAR(100),
    contact_person_name VARCHAR(255),
    contact_mobile VARCHAR(50),
    remarks TEXT,
    created_at DATETIME NOT NULL,
    INDEX idx_siding_code (siding_code)
);

CREATE TABLE reports (
    id VARCHAR(36) PRIMARY KEY,
    report_type VARCHAR(100),
    data TEXT,
    created_by VARCHAR(36),
    created_at DATETIME NOT NULL
);